name: Morefeatures
version: ${project.version}
main: me.morefeatures.morefeatures.Morefeatures
api-version: 1.16
authors: [chenjj100419]
website: chenjj100419.github.io/More_features/web/index.html
commands:
  setname:
    description: /setname [玩家(不要使用@a这些)] [自定义名字] 或者 /setname [自定义名字]
